// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectLibrary.Build.Service;

#nullable disable

namespace ProjectLibrary.Migrations
{
    [DbContext(typeof(Project1Dbcontext))]
    [Migration("20240118132716_Changed propertie AvgWinRate from double to decimal")]
    partial class ChangedpropertieAvgWinRatefromdoubletodecimal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjectLibrary.Build.Data.Calculator", b =>
                {
                    b.Property<int>("CalculatorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CalculatorId"));

                    b.Property<DateOnly>("CalculationDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("EditDate")
                        .HasColumnType("date");

                    b.Property<double>("FirstNum")
                        .HasColumnType("float");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Result")
                        .HasColumnType("float");

                    b.Property<double>("SecondNum")
                        .HasColumnType("float");

                    b.HasKey("CalculatorId");

                    b.ToTable("Calculators");
                });

            modelBuilder.Entity("ProjectLibrary.Build.Data.RPS", b =>
                {
                    b.Property<int>("RpsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RpsId"));

                    b.Property<decimal>("AvgWinRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ComputerMove")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ComputerScore")
                        .HasColumnType("int");

                    b.Property<DateOnly>("GameDate")
                        .HasColumnType("date");

                    b.Property<string>("PlayerMove")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlayerScore")
                        .HasColumnType("int");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RpsId");

                    b.ToTable("RockPaperScissor");
                });

            modelBuilder.Entity("ProjectLibrary.Build.Data.ShapeGame", b =>
                {
                    b.Property<int>("ShapeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShapeId"));

                    b.Property<double>("Area")
                        .HasColumnType("float");

                    b.Property<double>("Base")
                        .HasColumnType("float");

                    b.Property<double>("CathetusOne")
                        .HasColumnType("float");

                    b.Property<double>("CathetusTwo")
                        .HasColumnType("float");

                    b.Property<double>("Circumference")
                        .HasColumnType("float");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateOnly>("EditDate")
                        .HasColumnType("date");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<double>("Hypotenuse")
                        .HasColumnType("float");

                    b.Property<string>("ShapeForm")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ShapeId");

                    b.ToTable("Shapes");
                });
#pragma warning restore 612, 618
        }
    }
}
